version: '3.8'

services:
  travel-app:
    build: .
    container_name: travel-app
    ports:
      - "0.0.0.0:3000:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    labels:
      - "app=travel-app"
      - "environment=development"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/index_new.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a development server with hot reload
  dev-server:
    image: node:18-alpine
    container_name: travel-app-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8080:8080"
    command: >
      sh -c "
        npm install -g live-server &&
        live-server --host=0.0.0.0 --port=8080 --entry-file=index_new.html
      "
    profiles:
      - dev
    environment:
      - NODE_ENV=development

networks:
  default:
    name: travel-app-network